# Generated by Django 4.2.4 on 2023-08-24 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksapp', '0004_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrequest',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
