# Generated by Django 4.2.4 on 2023-08-26 09:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booksapp', '0005_borrowrequest_comments_borrowrequest_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowrequest',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='borrowrequest',
            name='response',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('time_send', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrowrequest',
            name='messages',
            field=models.ManyToManyField(blank=True, to='booksapp.message'),
        ),
    ]
